In [47]:
import pandas as pd
import numpy as np 

import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px 

import os
import re

%matplotlib inline

In [48]:
gff = pd.read_csv('/mnt/HC_Volume_18315164/home-jupyter/jupyter-k-alibekov/shared/homeworks/python_ds_miniprojects/6_gff/gff.tsv', sep='\t')

In [49]:
gff.head()

,seq_id,source,type,start,end,score,strand,phase,attributes
0,chr17,RefSeq,exon,6811330,6811453,.,+,.,Parent=XM_001475631.1
1,chr17,RefSeq,CDS,6808204,6808245,.,+,0,Name=CDS:NC_000083.5:LOC100040603;Parent=XM_00...
2,chr17,RefSeq,CDS,6811792,6811869,.,+,2,Name=CDS:NC_000083.5:LOC100040603;Parent=XM_00...
3,chr17,RefSeq,exon,6806513,6806553,.,+,.,Parent=XM_001475631.1
4,chr17,RefSeq,five_prime_UTR,6806513,6806526,.,+,.,Parent=XM_001475631.1

In [50]:
gff.dtypes

seq_id        object
source        object
type          object
start          int64
end            int64
score         object
strand        object
phase         object
attributes    object
dtype: object

In [63]:
gff['parent_name']= gff['attributes'].str.extract(r'Parent=(\w+.\w)')
gff.head()

,seq_id,source,type,start,end,score,strand,phase,attributes,parent_name
0,chr17,RefSeq,exon,6811330,6811453,.,+,.,Parent=XM_001475631.1,XM_001475631.1
1,chr17,RefSeq,CDS,6808204,6808245,.,+,0,Name=CDS:NC_000083.5:LOC100040603;Parent=XM_00...,XM_001475631.1
2,chr17,RefSeq,CDS,6811792,6811869,.,+,2,Name=CDS:NC_000083.5:LOC100040603;Parent=XM_00...,XM_001475631.1
3,chr17,RefSeq,exon,6806513,6806553,.,+,.,Parent=XM_001475631.1,XM_001475631.1
4,chr17,RefSeq,five_prime_UTR,6806513,6806526,.,+,.,Parent=XM_001475631.1,XM_001475631.1

In [64]:
gff.groupby('parent_name', as_index=False).agg({'seq_id':'count'}).sort_values('seq_id', ascending=False)

      parent_name  seq_id
1  XM_001475631.1     479
0     NC_000083.5      33

In [65]:
gff.groupby('type', as_index=False).agg({'seq_id':'count'}).sort_values('seq_id', ascending=False)

              type  seq_id
1             exon     201
0              CDS     170
2   five_prime_UTR      47
3             mRNA      33
5  three_prime_UTR      32
4          protein      29