In [17]:
import pandas as pd
import os

In [18]:
folder_data = [i for i in os.listdir('/mnt/HC_Volume_18315164/home-jupyter/jupyter-k-alibekov/shared/Res_Tree/') if not i.startswith('.')]

In [24]:
# for i in folder_data:
    # if i.startswith('.'):
        # continue
    # print(i)
    
# for i in folder_data:
    # if not i.startswith('.'):
        # print(i)
        
# [i for i in folder_data if not i.startswith('.')]

In [ ]:
# x = [1, 2, 'start', 3, 4, 'end', 5, 6, 'start', 7, 8, 'end']

# scanning = False

# for i in x:
#     if i == 'end':
#         scanning = False
#         continue
        
#     if scanning:
#         print(i)
        
#     if i == 'start':
#         scanning = True
#         continue

In [23]:
folder_data

['F000545', 'M000547', 'F000570']

In [32]:
path_to_file = '/mnt/HC_Volume_18315164/home-jupyter/jupyter-k-alibekov/shared/Res_Tree/F000545/res_2019.09.11_0.0_6493B6_Container-dat_2125_91-105-165_F000545/meals_list_2.txt'

In [54]:
all_data = []

In [55]:
scanning = False

for i in open(path_to_file).readlines():
    
    if i.startswith('--------------'):
        scanning = False
        continue
    
    if scanning:
        if 'Meal#;' in i:
            col_name = i
            continue
        all_data.append([value.strip() for value in i.split(';')])
    
    if 'Non-deleted saved meals' in i:
        scanning = True
        continue


# open(path_to_file).readlines()

In [47]:
col_name

' Meal#;        Date; Start;   End; Flags;    E-IN;    Cbh;    Fat;    Pro;  S. tstamp; End tstamp; Minutes;  Recs; First;  Last;    Type; Frags;\n'

In [56]:
final_col_names = [i.strip() for i in col_name.split(';')]

In [57]:
final_col_names

['Meal#',
 'Date',
 'Start',
 'End',
 'Flags',
 'E-IN',
 'Cbh',
 'Fat',
 'Pro',
 'S. tstamp',
 'End tstamp',
 'Minutes',
 'Recs',
 'First',
 'Last',
 'Type',
 'Frags',
 '']

In [59]:
all_data #список из списков

[['0',
  '09.01.2020',
  '10:54',
  '12:33',
  '0x84',
  '247.41',
  '18.85',
  '13.58',
  '12.45',
  '1578556469',
  '1578562439',
  '100',
  '100',
  '1',
  '100',
  'F3-Meal',
  ''],
 ['1',
  '09.01.2020',
  '12:42',
  '14:11',
  '0x84',
  '198.60',
  '17.00',
  '10.31',
  '9.45',
  '1578562921',
  '1578568288',
  '90',
  '94',
  '104',
  '197',
  'F3-Meal',
  ''],
 ['2',
  '09.01.2020',
  '14:31',
  '16:41',
  '0x84',
  '320.71',
  '23.09',
  '18.03',
  '16.53',
  '1578569494',
  '1578577272',
  '130',
  '130',
  '217',
  '346',
  'F3-Meal',
  ''],
 ['3',
  '09.01.2020',
  '16:57',
  '18:01',
  '0x84',
  '136.57',
  '12.71',
  '6.77',
  '6.20',
  '1578578237',
  '1578582096',
  '65',
  '65',
  '362',
  '426',
  'F3-Meal',
  ''],
 ['4',
  '09.01.2020',
  '18:09',
  '19:46',
  '0x84',
  '193.10',
  '16.25',
  '10.11',
  '9.27',
  '1578582579',
  '1578588367',
  '97',
  '97',
  '434',
  '530',
  'F3-Meal',
  ''],
 ['5',
  '09.01.2020',
  '20:43',
  '22:46',
  '0x84',
  '271.64',
  '19.42',
  '15.31',
  '14.04',
  '1578591804',
  '1578599161',
  '123',
  '103',
  '587',
  '689',
  'F3-Meal',
  ''],
 ['6',
  '09.01.2020',
  '22:46',
  '00:14',
  '0x84',
  '171.02',
  '15.29',
  '8.67',
  '7.95',
  '1578599161',
  '1578604467',
  '89',
  '101',
  '689',
  '789',
  'F3-Meal',
  ''],
 ['0',
  '09.01.2020',
  '22:46',
  '00:14',
  '0x84',
  '171.02',
  '15.29',
  '8.67',
  '7.95',
  '1578599161',
  '1578604467',
  '89',
  '101',
  '689',
  '789',
  'F3-Meal',
  ''],
 ['1',
  '10.01.2020',
  '01:22',
  '04:41',
  '0x84',
  '359.83',
  '29.25',
  '19.17',
  '17.57',
  '1578608567',
  '1578620506',
  '199',
  '203',
  '861',
  '1063',
  'F3-Meal',
  ''],
 ['2',
  '10.01.2020',
  '14:26',
  '15:48',
  '0x84',
  '167.74',
  '15.08',
  '8.48',
  '7.78',
  '1578655600',
  '1578660484',
  '82',
  '82',
  '1645',
  '1726',
  'F3-Meal',
  ''],
 ['3',
  '10.01.2020',
  '18:51',
  '19:58',
  '0x84',
  '171.56',
  '15.31',
  '8.71',
  '7.98',
  '1578671519',
  '1578675499',
  '67',
  '74',
  '1902',
  '1975',
  'F3-Meal',
  ''],
 ['4',
  '10.01.2020',
  '20:18',
  '21:31',
  '0x84',
  '149.40',
  '13.58',
  '7.51',
  '6.88',
  '1578676705',
  '1578681107',
  '74',
  '70',
  '1995',
  '2064',
  'F3-Meal',
  ''],
 ['5',
  '10.01.2020',
  '21:31',
  '23:07',
  '0x84',
  '190.85',
  '15.36',
  '10.22',
  '9.36',
  '1578681107',
  '1578686835',
  '96',
  '100',
  '2064',
  '2163',
  'F3-Meal',
  ''],
 ['6',
  '10.01.2020',
  '23:07',
  '01:16',
  '0x84',
  '308.65',
  '23.68',
  '16.89',
  '15.48',
  '1578686835',
  '1578694613',
  '130',
  '127',
  '2163',
  '2289',
  'F3-Meal',
  ''],
 ['0',
  '10.01.2020',
  '23:07',
  '01:16',
  '0x84',
  '308.65',
  '23.68',
  '16.89',
  '15.48',
  '1578686835',
  '1578694613',
  '130',
  '127',
  '2163',
  '2289',
  'F3-Meal',
  ''],
 ['1',
  '11.01.2020',
  '02:18',
  '03:00',
  '0x84',
  '51.46',
  '6.83',
  '1.91',
  '1.75',
  '1578698292',
  '1578700824',
  '43',
  '43',
  '2353',
  '2395',
  'F3-Meal',
  ''],
 ['2',
  '11.01.2020',
  '12:27',
  '15:10',
  '0x84',
  '404.28',
  '30.04',
  '22.43',
  '20.56',
  '1578734851',
  '1578744619',
  '163',
  '163',
  '2959',
  '3121',
  'F3-Meal',
  ''],
 ['3',
  '11.01.2020',
  '15:10',
  '17:57',
  '0x84',
  '430.73',
  '35.89',
  '22.67',
  '20.78',
  '1578744619',
  '1578754629',
  '167',
  '167',
  '3121',
  '3287',
  'F3-Meal',
  ''],
 ['4',
  '11.01.2020',
  '17:57',
  '19:24',
  '0x84',
  '210.59',
  '17.07',
  '11.24',
  '10.30',
  '1578754629',
  '1578759875',
  '88',
  '83',
  '3287',
  '3369',
  'F3-Meal',
  ''],
 ['5',
  '11.01.2020',
  '19:24',
  '21:14',
  '0x84',
  '253.52',
  '19.21',
  '13.95',
  '12.79',
  '1578759875',
  '1578766447',
  '110',
  '87',
  '3369',
  '3455',
  'F3-Meal',
  ''],
 ['6',
  '11.01.2020',
  '21:14',
  '00:13',
  '0x84',
  '427.87',
  '32.43',
  '23.54',
  '21.58',
  '1578766447',
  '1578777180',
  '179',
  '203',
  '3455',
  '3657',
  'F3-Meal',
  '']]

In [63]:
meal_df = pd.DataFrame(all_data, columns=final_col_names[0:17])

In [64]:
meal_df

,Meal#,Date,Start,End,Flags,E-IN,Cbh,Fat,Pro,S. tstamp,End tstamp,Minutes,Recs,First,Last,Type,Frags
0,0,09.01.2020,10:54,12:33,0x84,247.41,18.85,13.58,12.45,1578556469,1578562439,100,100,1,100,F3-Meal,
1,1,09.01.2020,12:42,14:11,0x84,198.60,17.00,10.31,9.45,1578562921,1578568288,90,94,104,197,F3-Meal,
2,2,09.01.2020,14:31,16:41,0x84,320.71,23.09,18.03,16.53,1578569494,1578577272,130,130,217,346,F3-Meal,
3,3,09.01.2020,16:57,18:01,0x84,136.57,12.71,6.77,6.20,1578578237,1578582096,65,65,362,426,F3-Meal,
4,4,09.01.2020,18:09,19:46,0x84,193.10,16.25,10.11,9.27,1578582579,1578588367,97,97,434,530,F3-Meal,
5,5,09.01.2020,20:43,22:46,0x84,271.64,19.42,15.31,14.04,1578591804,1578599161,123,103,587,689,F3-Meal,
6,6,09.01.2020,22:46,00:14,0x84,171.02,15.29,8.67,7.95,1578599161,1578604467,89,101,689,789,F3-Meal,
7,0,09.01.2020,22:46,00:14,0x84,171.02,15.29,8.67,7.95,1578599161,1578604467,89,101,689,789,F3-Meal,
8,1,10.01.2020,01:22,04:41,0x84,359.83,29.25,19.17,17.57,1578608567,1578620506,199,203,861,1063,F3-Meal,
9,2,10.01.2020,14:26,15:48,0x84,167.74,15.08,8.48,7.78,1578655600,1578660484,82,82,1645,1726,F3-Meal,
10,3,10.01.2020,18:51,19:58,0x84,171.56,15.31,8.71,7.98,1578671519,1578675499,67,74,1902,1975,F3-Meal,
11,4,10.01.2020,20:18,21:31,0x84,149.40,13.58,7.51,6.88,1578676705,1578681107,74,70,1995,2064,F3-Meal,
12,5,10.01.2020,21:31,23:07,0x84,190.85,15.36,10.22,9.36,1578681107,1578686835,96,100,2064,2163,F3-Meal,
13,6,10.01.2020,23:07,01:16,0x84,308.65,23.68,16.89,15.48,1578686835,1578694613,130,127,2163,2289,F3-Meal,
14,0,10.01.2020,23:07,01:16,0x84,308.65,23.68,16.89,15.48,1578686835,1578694613,130,127,2163,2289,F3-Meal,
15,1,11.01.2020,02:18,03:00,0x84,51.46,6.83,1.91,1.75,1578698292,1578700824,43,43,2353,2395,F3-Meal,
16,2,11.01.2020,12:27,15:10,0x84,404.28,30.04,22.43,20.56,1578734851,1578744619,163,163,2959,3121,F3-Meal,
17,3,11.01.2020,15:10,17:57,0x84,430.73,35.89,22.67,20.78,1578744619,1578754629,167,167,3121,3287,F3-Meal,
18,4,11.01.2020,17:57,19:24,0x84,210.59,17.07,11.24,10.30,1578754629,1578759875,88,83,3287,3369,F3-Meal,
19,5,11.01.2020,19:24,21:14,0x84,253.52,19.21,13.95,12.79,1578759875,1578766447,110,87,3369,3455,F3-Meal,
20,6,11.01.2020,21:14,00:13,0x84,427.87,32.43,23.54,21.58,1578766447,1578777180,179,203,3455,3657,F3-Meal,

In [102]:
meal_df.dtypes

Meal#                 object
Date          datetime64[ns]
Start                 object
End                   object
Flags                 object
E-IN                  object
Cbh                   object
Fat                   object
Pro                  float64
S. tstamp             object
End tstamp            object
Minutes                int64
Recs                  object
First                 object
Last                  object
Type                  object
Frags                 object
dtype: object

In [103]:
meal_df = meal_df.astype({'Minutes': 'int', 'Pro': 'float'})

In [104]:
meal_df['Date'] = pd.to_datetime(meal_df.Date, dayfirst=True)

In [105]:
user_meal_df = meal_df[['Date', 'Pro', 'Minutes']]

In [106]:
user_meal_df

         Date    Pro  Minutes
0  2020-09-01  12.45      100
1  2020-09-01   9.45       90
2  2020-09-01  16.53      130
3  2020-09-01   6.20       65
4  2020-09-01   9.27       97
5  2020-09-01  14.04      123
6  2020-09-01   7.95       89
7  2020-09-01   7.95       89
8  2020-10-01  17.57      199
9  2020-10-01   7.78       82
10 2020-10-01   7.98       67
11 2020-10-01   6.88       74
12 2020-10-01   9.36       96
13 2020-10-01  15.48      130
14 2020-10-01  15.48      130
15 2020-11-01   1.75       43
16 2020-11-01  20.56      163
17 2020-11-01  20.78      167
18 2020-11-01  10.30       88
19 2020-11-01  12.79      110
20 2020-11-01  21.58      179

In [107]:
user_meal_df.dtypes

Date       datetime64[ns]
Pro               float64
Minutes             int64
dtype: object

In [108]:
user_meal_df.Date.dt.daysinmonth

0     30
1     30
2     30
3     30
4     30
5     30
6     30
7     30
8     31
9     31
10    31
11    31
12    31
13    31
14    31
15    30
16    30
17    30
18    30
19    30
20    30
Name: Date, dtype: int64

In [91]:
df = user_meal_df.groupby('Date', as_index=False).agg({'Minutes': 'sum'})

In [92]:
df.to_csv('df_minutes.csv', index=False)

In [109]:
os.getcwd()

'/mnt/HC_Volume_18315164/home-jupyter/jupyter-k-alibekov/personal'

In [113]:
# ~ – это домашняя директория, позволяющая создать абсолютный путь к файлу